if(ENABLE_EXCEPTION_HANDLER)
	target_compile_definitions(${CMAKE_PROJECT_NAME} PRIVATE ENABLE_EXCEPTION_HANDLER)
endif()

target_compile_definitions(${CMAKE_PROJECT_NAME} PRIVATE PROJECT_NAME="${CMAKE_PROJECT_NAME}")
